# Generated by Django 4.2 on 2024-09-16 13:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customAdmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('stu_no', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('phone_no', models.CharField(max_length=10, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)])),
                ('adhar_no', models.CharField(blank=True, max_length=12, unique=True, validators=[django.core.validators.MaxLengthValidator(12), django.core.validators.MinLengthValidator(12)])),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('alloted', 'Alloted'), ('suspended', 'Suspended')], default='enrolled', editable=False, max_length=10)),
                ('created_by', models.ForeignKey(blank=True, default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
            bases=('customAdmin.customuser',),
        ),
    ]
