# Generated by Django 4.2 on 2024-09-04 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_is_staff_remove_student_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='adhar_no',
            field=models.CharField(blank=True, max_length=12, unique=True, validators=[django.core.validators.MaxLengthValidator(12), django.core.validators.MinLengthValidator(12)]),
        ),
    ]
