# Generated by Django 4.2 on 2024-09-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_name_alter_student_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('alloted', 'Alloted'), ('suspended', 'Suspended')], default='enrolled', editable=False, max_length=10),
        ),
    ]
