# Generated by Django 4.2 on 2024-09-16 13:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('extended_date', models.DateTimeField(blank=True, null=True)),
                ('joining_date', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', editable=False, max_length=10)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seat Booking',
                'verbose_name_plural': 'Seat Bookings',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Library Id')),
                ('location_name', models.CharField(max_length=100, verbose_name='Library Name')),
                ('timming', models.CharField(choices=[('full', 'Full Day'), ('custom', 'Custom timming')], default='full', max_length=10)),
                ('opening_time', models.PositiveIntegerField(blank=True, choices=[(4, '4:00 AM Morning'), (5, '5:00 AM Morning'), (6, '6:00 AM Morning'), (7, '7:00 AM'), (8, '8:00 AM'), (9, '9:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 PM (noon)'), (13, '1:00 PM'), (14, '2:00 PM'), (15, '3:00 PM'), (16, '4:00 PM'), (17, '5:00 PM'), (18, '6:00 PM'), (19, '7:00 PM'), (20, '8:00 PM Night'), (21, '9:00 PM Night'), (22, '10:00 PM Night'), (23, '11:00 PM Night)]'), (0, '12:00 AM, midnight Night'), (1, '1:00 AM Night'), (2, '2:00 AM Night'), (3, '3:00 AM Night')], null=True, verbose_name='Opening Time(leave it blank for full time)')),
                ('closing_time', models.PositiveIntegerField(blank=True, choices=[(4, '4:00 AM Morning'), (5, '5:00 AM Morning'), (6, '6:00 AM Morning'), (7, '7:00 AM'), (8, '8:00 AM'), (9, '9:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 PM (noon)'), (13, '1:00 PM'), (14, '2:00 PM'), (15, '3:00 PM'), (16, '4:00 PM'), (17, '5:00 PM'), (18, '6:00 PM'), (19, '7:00 PM'), (20, '8:00 PM Night'), (21, '9:00 PM Night'), (22, '10:00 PM Night'), (23, '11:00 PM Night)]'), (0, '12:00 AM, midnight Night'), (1, '1:00 AM Night'), (2, '2:00 AM Night'), (3, '3:00 AM Night')], null=True, verbose_name='Closing Time(leave it blank for full time)')),
                ('discription', models.TextField(blank=True, null=True)),
                ('number_of_seats', models.PositiveIntegerField(verbose_name='No of Seats')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('exposed', 'Exposed')], default='active', max_length=10)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'library',
                'verbose_name_plural': 'libraries',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Seat Id')),
                ('seat_no', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Seat No')),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], default='vacant', max_length=10)),
                ('deleted', models.BooleanField(blank=None, default=False, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.location', verbose_name='Location no.')),
            ],
            options={
                'verbose_name': 'Seat',
                'verbose_name_plural': 'Seats',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Location No')),
                ('payment_type', models.CharField(choices=[('seat_book', 'Seat Bookijng'), ('user_pay', 'User Payement')], max_length=10, verbose_name='Type Of Payment')),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Amount (₹)')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount to be paid')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Discount (in %)')),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('creditoruser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creditor_payments', to=settings.AUTH_USER_MODEL)),
                ('debitoruser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debitor_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='MonthlyPlan',
            fields=[
                ('timming_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Location No')),
                ('hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='No. of hours')),
                ('planing_for', models.CharField(choices=[('d', 'DAYS'), ('w', 'WEEKS'), ('m', 'MONTHS')], default='m', max_length=10)),
                ('duration', models.PositiveIntegerField(default=1, verbose_name='Duration (no. Days/Months/Weeks)')),
                ('prize', models.PositiveIntegerField(verbose_name='Price(in rupees)')),
                ('discription', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', editable=False, max_length=10)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Plan',
                'verbose_name_plural': 'Monthly Plans',
            },
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_payments', to='booking.booking')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.payment')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.seat'),
        ),
        migrations.AddField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='students.student'),
        ),
    ]
