# Generated by Django 4.2 on 2024-08-29 13:20

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=booking.models.Student.user_avatar_upload_to),
        ),
    ]
