# Generated by Django 4.2 on 2024-08-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_no',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Seat No'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Seat Id'),
        ),
    ]
