# Generated by Django 4.2 on 2024-09-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplan',
            name='plan_of_time',
            field=models.CharField(choices=[('d', 'DAYS'), ('w', 'WEEKS'), ('m', 'MONTHS')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Library Id'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=100, verbose_name='Library Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('exposed', 'Exposed')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='prize',
            field=models.PositiveIntegerField(verbose_name='Price(in rupees)'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='deleted',
            field=models.BooleanField(blank=None, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], default='vacant', max_length=10),
        ),
    ]
