# Generated by Django 5.1 on 2024-08-08 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_location_number_of_seats_alter_seat_seat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='deleted',
            field=models.BooleanField(blank=None, default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='number_of_seats',
            field=models.PositiveIntegerField(verbose_name='No of Seats'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.location', verbose_name='Location no.'),
        ),
    ]
