# Generated by Django 4.2 on 2024-08-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_seat_seat_no_alter_seat_seat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
