# Generated by Django 5.1 on 2024-08-10 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_seat_deleted_alter_location_number_of_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'closed')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('engaged', 'Engaged'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('inrolled', 'Inrolled'), ('alloted', 'Alloted'), ('suspended', 'Suspended')], default='active', max_length=10),
        ),
    ]
