# Generated by Django 4.2 on 2024-09-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_monthlyplan_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyplan',
            name='plan_of_time',
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='planing_for',
            field=models.CharField(choices=[('d', 'DAYS'), ('w', 'WEEKS'), ('m', 'MONTHS')], default='m', max_length=10),
        ),
    ]
