# Generated by Django 4.2 on 2024-08-20 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0003_student_stu_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monthly_prizing',
            new_name='MonthlyPlan',
        ),
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Seat Booking', 'verbose_name_plural': 'Seat Bookings'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='monthlyplan',
            options={'verbose_name': 'Monthly Plan', 'verbose_name_plural': 'Monthly Plans'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'verbose_name': 'Seat', 'verbose_name_plural': 'Seats'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_no',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Seat No'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_no',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
