# Generated by Django 5.1 on 2024-08-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_duration_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('engaged', 'Engaged'), ('inactive', 'Inactive')], default='vacant', max_length=10),
        ),
    ]
