# Generated by Django 5.1 on 2024-08-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_rename_user_booking_student_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
