# Generated by Django 4.2 on 2024-08-20 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_joining_date_booking_remain_no_of_months'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='booking_to_update',
            new_name='booking',
        ),
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Monthly price(in rupees)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 20, 9, 27, 10, 617984, tzinfo=datetime.timezone.utc), verbose_name='Joining from'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='remain_no_of_months',
            field=models.PositiveIntegerField(default=1, verbose_name='No. of Months'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='prize',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Monthly price(in rupees)'),
        ),
    ]
