# Generated by Django 4.2 on 2024-09-05 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_monthlyplan_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extended_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.seat'),
        ),
        migrations.AlterField(
            model_name='location',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='duration',
            field=models.PositiveIntegerField(default=1, verbose_name='Duration (no. Days/Months/Weeks)'),
        ),
    ]
