# Generated by Django 4.2 on 2024-08-20 14:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_rename_booking_to_update_payment_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 20, 14, 14, 56, 99994, tzinfo=datetime.timezone.utc), verbose_name='Joining from'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='remain_no_of_months',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='No. of Months'),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='hours',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='No. of hours'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Monthly price(in rupees)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='prize',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Monthly price(in rupees)'),
        ),
    ]
