# Generated by Django 4.2 on 2024-08-22 05:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_joining_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='prize',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Amount (₹)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Paid Amount (₹)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 22, 5, 12, 36, 618513, tzinfo=datetime.timezone.utc), verbose_name='Joining from'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Discount (in %)'),
        ),
    ]
