# Generated by Django 4.2 on 2024-09-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_seat_alter_booking_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='closing_time',
            field=models.PositiveIntegerField(blank=True, choices=[(4, '4:00 AM Morning'), (5, '5:00 AM Morning'), (6, '6:00 AM Morning'), (7, '7:00 AM'), (8, '8:00 AM'), (9, '9:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 PM (noon)'), (13, '1:00 PM'), (14, '2:00 PM'), (15, '3:00 PM'), (16, '4:00 PM'), (17, '5:00 PM'), (18, '6:00 PM'), (19, '7:00 PM'), (20, '8:00 PM'), (21, '9:00 PM'), (22, '10:00 PM'), (23, '11:00 PM)]'), (24, '12:00 AM, midnight'), (1, '1:00 AM'), (2, '2:00 AM'), (3, '3:00 AM')], null=True, verbose_name='Closing Time'),
        ),
        migrations.AddField(
            model_name='location',
            name='opening_time',
            field=models.PositiveIntegerField(blank=True, choices=[(4, '4:00 AM Morning'), (5, '5:00 AM Morning'), (6, '6:00 AM Morning'), (7, '7:00 AM'), (8, '8:00 AM'), (9, '9:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 PM (noon)'), (13, '1:00 PM'), (14, '2:00 PM'), (15, '3:00 PM'), (16, '4:00 PM'), (17, '5:00 PM'), (18, '6:00 PM'), (19, '7:00 PM'), (20, '8:00 PM'), (21, '9:00 PM'), (22, '10:00 PM'), (23, '11:00 PM)]'), (24, '12:00 AM, midnight'), (1, '1:00 AM'), (2, '2:00 AM'), (3, '3:00 AM')], null=True, verbose_name='Opening Time'),
        ),
    ]
