# Generated by Django 4.2 on 2024-08-22 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_payment_prize_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 22, 5, 14, 19, 595211, tzinfo=datetime.timezone.utc), verbose_name='Joining from'),
        ),
    ]
