# Generated by Django 4.2 on 2024-08-22 09:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_joining_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='remain_no_of_months',
        ),
        migrations.AddField(
            model_name='payment',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 22, 9, 28, 13, 710017, tzinfo=datetime.timezone.utc), verbose_name='Joining from'),
        ),
        migrations.AddField(
            model_name='payment',
            name='remain_no_of_months',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='No. of Months'),
        ),
    ]
