# Generated by Django 5.1 on 2024-08-25 13:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_payment_joining_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'library', 'verbose_name_plural': 'libraries'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 25, 13, 32, 44, 403094, tzinfo=datetime.timezone.utc), verbose_name='Joining from'),
        ),
    ]
