name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to Server
        run: |
          SSH_PRIVATE_KEY=$(cat /home/myLibraryprojectuser/.ssh/id_ed25519)
          chmod 600 /home/myLibraryprojectuser/.ssh/id_ed25519
          ssh -i /home/myLibraryprojectuser/.ssh/id_ed25519 -o StrictHostKeyChecking=no myLibraryprojectuser@157.173.221.214 "cd /home/applications/myLibrary && git pull origin master && ./deploy.sh"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
